apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enketo.fullname" . }}
  labels:
    {{- include "enketo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "enketo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/express.js: {{ .Values.expressConfig | default (.Files.Get "config/express.js") | sha256sum | quote }}
        checksum/startup.sh: {{ .Values.initFile | default (.Files.Get "config/startup.sh") | sha256sum | quote }}
        checksum/default-config.json: {{ .Values.settingsConfig | default (.Files.Get "config/default-config.json") | sha256sum | quote }}
        checksum/config.json: {{ .Values.settingsConfig | default (.Files.Get "config/config.json") | sha256sum | quote }}
        checksum/build.js: {{ .Values.buildConfig | default (.Files.Get "config/build.js") | sha256sum | quote }}
        {{- if .Values.recreatePods }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "enketo.selectorLabels" . | nindent 8 }}{{- with .Values.extraSelectorLabels}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enketo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: app-configs
          configMap:
            name: {{ include "enketo.fullname" . }}-config-files
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: app-configs
              mountPath: /srv/src/enketo_express/config
          command: ["/bin/bash", "-c"]
          args:
            - "/srv/src/enketo_express/config/startup.sh"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            {{- if .Values.extraEnvVars }}
          env:
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
          {{- if or .Values.extraSecretEnvVars .Values.createExtraSecretEnvVarsSecret -}}
          envFrom:
            secrets:
              - name: {{ .Values.extraSecretEnvVarsSecretName }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
