apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enketo.fullname" . }}
  labels:
    {{- include "enketo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "enketo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/initFile: {{ .Values.initFile | sha256sum }}
        checksum/expressConfig: {{ .Values.expressConfig | sha256sum }}
        checksum/settingsConfig: {{ .Values.settingsConfig | sha256sum }}
        checksum/buildConfig: {{ .Values.buildConfig | sha256sum }}
        {{- if .Values.recreatePods }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "enketo.selectorLabels" . | nindent 8 }}{{- with .Values.extraSelectorLabels}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enketo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: app-configs
          secret:
            secretName: {{ .Values.configSecretName }}
            defaultMode: 0777
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: app-configs
              mountPath: /srv/src/enketo/packages/enketo-express/config
          command: [ "/bin/bash", "-c" ]
          args:
            - "/srv/src/enketo/packages/enketo-express/config/startup.sh"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
