apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecretName }}
  labels:
    {{- include "enketo.labels" . | nindent 4 }}
type: Opaque
type: Opaque
data:
    express.js: {{ .Values.expressConfig | b64enc | quote }}
    startup.sh: {{ .Values.initFile | b64enc | quote }}
    default-config.json: {{ .Values.settingsConfig | b64enc | quote }}
    config.json: {{ .Values.settingsConfig | b64enc | quote }}
    build.js: {{ .Values.buildConfig | b64enc | quote }}
